### ISSUE TITLE
H2 does not display on primary notices

### ISSUE THREAD

**Issue by faulteh** [chimo/gs-markdown#5]
Hi, thanks for the nice simple module.

It looks like h2 on the notices pages won't display because the base/display.css has

```css
#notices_primary h2 {   
    display: none;
}
```
While it does display on the user's profile page (as that uses the "notices" class not "notices_primary")

Perhaps we will need a Markdown compatible theme to go along with the plugin?

(My test site here http://taslug.org.au)
